services:
  - type: web
    name: organ-donation-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT backend.asgi:application
    healthCheckPath: /admin/login/
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: organ-donation-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: organ-donation-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: organ-donation-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://organ-donation-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://organ-donation-backend.onrender.com,https://organ-donation-frontend.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: CSRF_COOKIE_SECURE
        value: "true"
  - type: redis
    name: organ-donation-redis
    ipAllowList: []
  - type: worker
    name: organ-donation-migrate
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: >
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput
    autoDeploy: false
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: organ-donation-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: organ-donation-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: organ-donation-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://organ-donation-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://organ-donation-backend.onrender.com,https://organ-donation-frontend.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: CSRF_COOKIE_SECURE
        value: "true"
databases:
  - name: organ-donation-postgres
    plan: free

