# Generated by Django 5.1.7 on 2025-05-21 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('request_sent', 'Request Sent'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('organ_listed', 'Organ Listed'), ('organ_edited', 'Organ Edited'), ('organ_deleted', 'Organ Deleted'), ('profile_edited', 'Profile Edited'), ('device_login', 'Login from New Device'), ('message_sent', 'Message Sent'), ('search_performed', 'Search Performed'), ('organ_marked_unavailable', 'Organ Marked Unavailable'), ('request_cancelled', 'Request Cancelled')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_ac_user_id_5cc398_idx'), models.Index(fields=['activity_type'], name='activity_ac_activit_603290_idx'), models.Index(fields=['is_read'], name='activity_ac_is_read_a2909b_idx')],
            },
        ),
    ]
