# Generated by Django 5.1.7 on 2025-05-21 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(choices=[('kidney', 'Kidney'), ('liver', 'Liver'), ('heart', 'Heart'), ('lung', 'Lung'), ('pancreas', 'Pancreas'), ('intestine', 'Intestine'), ('cornea', 'Cornea'), ('skin', 'Skin'), ('bone', 'Bone'), ('bone_marrow', 'Bone_Marrow')], max_length=50)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('location', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, help_text='Anonymous identifier for the donor', max_length=50, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='donations.organ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_connections', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_connections', to=settings.AUTH_USER_MODEL)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='donations.organ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(blank=True, choices=[('kidney', 'Kidney'), ('liver', 'Liver'), ('heart', 'Heart'), ('lung', 'Lung'), ('pancreas', 'Pancreas'), ('intestine', 'Intestine'), ('cornea', 'Cornea'), ('skin', 'Skin'), ('bone', 'Bone'), ('bone_marrow', 'Bone_Marrow')], max_length=50, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('urgency_level', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_type_match', models.JSONField()),
                ('age_match', models.JSONField()),
                ('height_match', models.JSONField()),
                ('weight_match', models.JSONField(blank=True, null=True)),
                ('location_match', models.JSONField()),
                ('is_notified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.organ')),
                ('recipient_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.recipientrequest')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddIndex(
            model_name='organ',
            index=models.Index(fields=['is_available'], name='donations_o_is_avai_26233a_idx'),
        ),
        migrations.AddIndex(
            model_name='organ',
            index=models.Index(fields=['location'], name='donations_o_locatio_898ada_idx'),
        ),
        migrations.AddIndex(
            model_name='organ',
            index=models.Index(fields=['blood_type'], name='donations_o_blood_t_86037b_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['status'], name='donations_c_status_d9d05b_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['donor', 'recipient'], name='donations_c_donor_i_7a1e15_idx'),
        ),
        migrations.AddIndex(
            model_name='organmatch',
            index=models.Index(fields=['match_score'], name='donations_o_match_s_142ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='organmatch',
            index=models.Index(fields=['organ', 'recipient_request'], name='donations_o_organ_i_b2a258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organmatch',
            unique_together={('organ', 'recipient_request')},
        ),
    ]
